# Generated by Django 2.2 on 2019-06-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='content',
            field=models.CharField(blank=True, max_length=128, verbose_name='content'),
        ),
        migrations.AlterUniqueTogether(
            name='roomuser',
            unique_together={('user', 'room')},
        ),
    ]
