# Generated by Django 2.2.2 on 2019-06-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190626_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=32, verbose_name='label uuid')),
                ('content', models.CharField(blank=True, max_length=128, verbose_name='content')),
            ],
            options={
                'verbose_name': 'RoomIp',
                'verbose_name_plural': 'RoomIp',
            },
        ),
        migrations.CreateModel(
            name='UserIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(blank=True, default=False)),
                ('ip', models.GenericIPAddressField()),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='username')),
            ],
            options={
                'verbose_name': 'UserIp',
                'verbose_name_plural': 'UserIp',
            },
        ),
        migrations.AddIndex(
            model_name='userip',
            index=models.Index(fields=['ip'], name='chat_userip_ip_7b3863_idx'),
        ),
        migrations.AddIndex(
            model_name='userip',
            index=models.Index(fields=['username'], name='chat_userip_usernam_485985_idx'),
        ),
        migrations.AddIndex(
            model_name='roomip',
            index=models.Index(fields=['label'], name='chat_roomip_label_f14e03_idx'),
        ),
        migrations.AddIndex(
            model_name='roomip',
            index=models.Index(fields=['create_time'], name='chat_roomip_create__98bf04_idx'),
        ),
    ]
