# Generated by Django 2.2.2 on 2019-06-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190627_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomUserIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('room_ip_id', models.IntegerField(blank=True, default=0, verbose_name='roomIp_id')),
                ('is_online', models.BooleanField(blank=True, default=False, verbose_name='is_online')),
                ('connect_time', models.DateTimeField(auto_now_add=True, verbose_name='connect_time')),
                ('disconnect_time', models.DateTimeField(blank=True, null=True, verbose_name='disconnect_time')),
            ],
            options={
                'verbose_name': 'RoomUserIp',
                'verbose_name_plural': 'RoomUserIp',
            },
        ),
        migrations.AlterField(
            model_name='userip',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AddIndex(
            model_name='roomuserip',
            index=models.Index(fields=['ip'], name='chat_roomus_ip_e842b8_idx'),
        ),
        migrations.AddIndex(
            model_name='roomuserip',
            index=models.Index(fields=['room_ip_id'], name='chat_roomus_room_ip_69ff3a_idx'),
        ),
        migrations.AddIndex(
            model_name='roomuserip',
            index=models.Index(fields=['is_online'], name='chat_roomus_is_onli_c01e87_idx'),
        ),
        migrations.AddIndex(
            model_name='roomuserip',
            index=models.Index(fields=['connect_time'], name='chat_roomus_connect_a6d744_idx'),
        ),
    ]
