# Generated by Django 2.2.2 on 2019-06-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_roomuserip_last_connect_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuserip',
            name='client_port',
            field=models.CharField(blank=True, max_length=16, verbose_name='port'),
        ),
        migrations.AddIndex(
            model_name='roomuserip',
            index=models.Index(fields=['client_port'], name='chat_roomus_client__096954_idx'),
        ),
    ]
