# Generated by Django 2.2.2 on 2019-06-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190627_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomuserip',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='roomuserip',
            unique_together={('ip', 'client_port')},
        ),
    ]
