# Generated by Django 2.2.2 on 2019-07-01 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20190627_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(blank=True, default=False)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BlackIp',
                'verbose_name_plural': 'BlackIp',
            },
        ),
        migrations.CreateModel(
            name='MessageIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=0, verbose_name='UserId')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='send time')),
                ('is_show', models.BooleanField(blank=True, default=True, verbose_name='if show')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.RoomIp')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Message',
            },
        ),
        migrations.AddIndex(
            model_name='blackip',
            index=models.Index(fields=['ip'], name='chat_blacki_ip_4303e1_idx'),
        ),
        migrations.AddIndex(
            model_name='messageip',
            index=models.Index(fields=['send_time'], name='chat_messag_send_ti_351757_idx'),
        ),
        migrations.AddIndex(
            model_name='messageip',
            index=models.Index(fields=['user_id'], name='chat_messag_user_id_94c2de_idx'),
        ),
    ]
