# Generated by Django 2.2.2 on 2019-07-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20190701_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageip',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.RoomIp'),
        ),
    ]
